# Generated by Django 3.1.7 on 2021-04-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='size',
            field=models.CharField(default='DEFAULT VALUE', max_length=100),
        ),
    ]
