# Generated by Django 3.1.7 on 2021-04-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210406_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
